import { useState } from 'react';
import { 
  Users, 
  UserCheck, 
  ShieldCheck, 
  PhoneCall, 
  FileText, 
  Clock, 
  BarChart3, 
  CheckCircle2, 
  ArrowRight,
  Shield,
  Layers,
  Sparkles,
  AlertTriangle
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface WorkflowStep {
  id: number;
  label: string;
  sublabel: string;
  icon: any;
  actionTitle: string;
  description: string;
  traditionalFailure: string;
  dialpulseAdvantage: string;
  modules: string[];
}

const workflowSteps: WorkflowStep[] = [
  {
    id: 0,
    label: 'LEAD ARRIVES',
    sublabel: 'Webhook / CSV Batch',
    icon: Users,
    actionTitle: 'Ingestion & Schema Normalization',
    description: 'Raw inbound contacts enter through webhook integrations or bulk CSV uploads. The ingestion engine automatically validates phone numbers, checks for duplicates, and maps custom properties.',
    traditionalFailure: 'Spreadsheet chaos; duplicates flood the database; hours or days pass before anyone reviews the new inquiries.',
    dialpulseAdvantage: 'Instant deduplication and automatic assignment to configured sales pipeline stages in milliseconds.',
    modules: ['Leads', 'Imports']
  },
  {
    id: 1,
    label: 'ASSIGNED TO TEAM',
    sublabel: 'RBAC & Round-Robin',
    icon: UserCheck,
    actionTitle: 'Dynamic Telecaller Assignment',
    description: 'Leads are routed to active telecallers based on pipeline criteria or round-robin logic. Team Leads supervise the queue in real time.',
    traditionalFailure: 'Leads assigned to agents on leave or vacation sit untouched with zero supervisor visibility.',
    dialpulseAdvantage: 'Live agent presence tracking allows supervisors to reallocate stalled leads with two clicks.',
    modules: ['Teams', 'Users', 'Administration']
  },
  {
    id: 2,
    label: 'COMPLIANCE CHECK',
    sublabel: 'DNC & Quiet Hours',
    icon: ShieldCheck,
    actionTitle: 'Zero-Bypass Policy Verification',
    description: 'Before dialing or messaging begins, the policy engine verifies the recipient against national/tenant Do-Not-Call lists and checks local legal calling hours.',
    traditionalFailure: 'Reps accidentally dial prospects at 9:00 PM or contact numbers registered on federal DNC registries.',
    dialpulseAdvantage: 'Hard code-level lockout physically disables dialing if a number is on DNC or outside permitted hours.',
    modules: ['Compliance', 'Calls']
  },
  {
    id: 3,
    label: 'CONTACTED',
    sublabel: 'WebRTC / Fallback MSG',
    icon: PhoneCall,
    actionTitle: 'In-Browser Telephony & Fallback',
    description: 'Telecallers dial directly inside the browser using WebRTC audio. If unanswered, an automated WhatsApp or SMS template is dispatched immediately.',
    traditionalFailure: 'Reps dial from personal mobile phones; conversations are untracked; zero record exists of missed attempts.',
    dialpulseAdvantage: 'Browser-based softphone with dual-track audio recording and instant fallback messaging in one unified view.',
    modules: ['Calls', 'Messages']
  },
  {
    id: 4,
    label: 'CONVERSATION CONTEXT',
    sublabel: 'Private Tenant AI',
    icon: Sparkles,
    actionTitle: 'Private AI Summarization & Notes',
    description: 'During and after the call, interaction notes and audio transcripts are processed within the private tenant perimeter to extract key requirements and customer sentiment.',
    traditionalFailure: 'Reps jot hasty, illegible notes or forget to write anything at all, losing key qualification criteria.',
    dialpulseAdvantage: 'Automated bullet-point extraction (budget, decision makers, objections) without data leakage.',
    modules: ['AI', 'Calls', 'Leads']
  },
  {
    id: 5,
    label: 'FOLLOW-UP DISCIPLINE',
    sublabel: 'Scheduled Alerts',
    icon: Clock,
    actionTitle: 'Mandatory Callback Cadence',
    description: 'Calls cannot be closed without a verified disposition tag. Scheduled callbacks trigger notification alerts directly in the agent’s softphone drawer.',
    traditionalFailure: 'Over 60% of interested leads drop off because reps forget to make the second or third follow-up call.',
    dialpulseAdvantage: 'Structured follow-up reminders and automated multi-touch queues keep pipeline momentum alive.',
    modules: ['Leads', 'Calls', 'Messages']
  },
  {
    id: 6,
    label: 'REPORTING & REVENUE',
    sublabel: 'Async Analytics',
    icon: BarChart3,
    actionTitle: 'Operational Insights & Closed Deals',
    description: 'Managers view live dashboards on connection rates and handle times. Heavy analytical audits and CSV logs are generated by asynchronous background workers.',
    traditionalFailure: 'Reporting reports take weeks to assemble manually or cause database crashes when querying historical tables.',
    dialpulseAdvantage: 'Zero-lag asynchronous reporting engine delivers accurate pipeline analytics and verified audit exports.',
    modules: ['Reports', 'Teams', 'Leads']
  }
];

export function SolutionsWorkflowVisual() {
  const [activeStepId, setActiveStepId] = useState(0);
  const activeStep = workflowSteps[activeStepId];

  return (
    <div className="w-full bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 lg:p-12 shadow-sm">
      
      {/* Header */}
      <div className="max-w-3xl mb-10">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-teal-50 border border-teal-200 text-[#00695C] text-xs font-mono font-semibold uppercase tracking-wider mb-3">
          <Layers className="w-3.5 h-3.5" />
          End-to-End Operational Lifecycle
        </div>
        <h2 className="text-2xl sm:text-4xl font-display font-bold text-slate-900 tracking-tight">
          How Customer Workflows Flow Through DialPulse
        </h2>
        <p className="text-slate-600 text-base sm:text-lg mt-2 leading-relaxed">
          From the initial webhook ingestion to compliance locking, softphone dialing, AI synthesis, and async reporting—click any stage below to inspect the operational difference.
        </p>
      </div>

      {/* Horizontal Interactive Steps Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2 mb-8 pb-4 border-b border-slate-100">
        {workflowSteps.map((step) => {
          const Icon = step.icon;
          const isActive = step.id === activeStepId;
          return (
            <button
              key={step.id}
              onClick={() => setActiveStepId(step.id)}
              className={cn(
                'p-3 rounded-xl border text-left transition-all cursor-pointer flex flex-col justify-between',
                isActive
                  ? 'bg-slate-900 text-white border-slate-900 shadow-md ring-2 ring-[#00695C]/20'
                  : 'bg-slate-50/80 hover:bg-slate-100 border-slate-200/80 text-slate-700'
              )}
            >
              <div className="flex items-center justify-between mb-2">
                <span className={cn(
                  'text-[10px] font-mono font-bold px-1.5 py-0.5 rounded',
                  isActive ? 'bg-teal-400 text-slate-950' : 'bg-slate-200 text-slate-600'
                )}>
                  0{step.id + 1}
                </span>
                <Icon className={cn('w-4 h-4', isActive ? 'text-teal-300' : 'text-slate-400')} />
              </div>
              <div>
                <div className={cn('text-xs font-bold font-display leading-tight', isActive ? 'text-white' : 'text-slate-900')}>
                  {step.label}
                </div>
                <div className={cn('text-[10px] truncate mt-0.5 font-mono', isActive ? 'text-slate-400' : 'text-slate-500')}>
                  {step.sublabel}
                </div>
              </div>
            </button>
          );
        })}
      </div>

      {/* Active Workflow Inspection Card */}
      <div className="bg-slate-50/80 rounded-2xl border border-slate-200/90 p-6 sm:p-8 lg:p-10 space-y-6">
        
        <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-slate-200/80">
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono font-bold px-2.5 py-1 rounded bg-[#00695C] text-white">
              STAGE 0{activeStep.id + 1} OF 07
            </span>
            <span className="text-sm font-bold font-display text-slate-900">
              {activeStep.actionTitle}
            </span>
          </div>

          <div className="flex items-center gap-1.5 text-xs font-mono text-slate-500">
            <span>Modules:</span>
            {activeStep.modules.map((m, i) => (
              <span key={i} className="px-2 py-0.5 rounded bg-white border border-slate-200 font-semibold text-[#00695C]">
                {m}
              </span>
            ))}
          </div>
        </div>

        <p className="text-slate-700 text-base leading-relaxed">
          {activeStep.description}
        </p>

        {/* Side-by-Side: Traditional CRM Breakdown vs DialPulse Advantage */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
          
          <div className="p-4 rounded-xl bg-white border border-rose-200/90 shadow-2xs">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-rose-700 uppercase mb-1.5">
              <AlertTriangle className="w-3.5 h-3.5" />
              Where Disjointed Systems Fail
            </div>
            <p className="text-xs text-slate-600 leading-relaxed">
              {activeStep.traditionalFailure}
            </p>
          </div>

          <div className="p-4 rounded-xl bg-white border border-teal-200/90 shadow-2xs">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-[#00695C] uppercase mb-1.5">
              <CheckCircle2 className="w-3.5 h-3.5" />
              The DialPulse Operating Advantage
            </div>
            <p className="text-xs text-slate-700 font-medium leading-relaxed">
              {activeStep.dialpulseAdvantage}
            </p>
          </div>

        </div>

        <div className="flex items-center justify-between pt-4 border-t border-slate-200 text-xs font-mono text-slate-500">
          <span>Continuous Workflow State Engine</span>
          <button
            onClick={() => setActiveStepId((prev) => (prev + 1) % workflowSteps.length)}
            className="inline-flex items-center gap-1.5 font-semibold text-[#00695C] hover:text-[#004D40] transition-colors cursor-pointer"
          >
            <span>Next Stage: {workflowSteps[(activeStepId + 1) % workflowSteps.length].label}</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </button>
        </div>

      </div>

    </div>
  );
}
